#!/usr/bin/env python3
"""
plot_all.py
===========

Recreate the four main figures of Linden et al. (2026) **using the real
1-year Fermi-LAT data products** generated by the analysis pipeline.

Expected input
--------------
results/real_data.pkl   (written automatically by the pipeline)

Figures written
---------------
plots/output/fig1_spectrum_morphology.{png,pdf}
plots/output/fig2_helioprojective_maps.{png,pdf}
plots/output/fig3_spectra_radial_bins.{png,pdf}
plots/output/fig4_radial_profiles_energy_bins.{png,pdf}
"""

from pathlib import Path
import sys, os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import LogNorm

# -------------------------------------------------------------------
#  Local imports
# -------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[1]          # …/solar_halo_project
sys.path.insert(0, str(ROOT))                      # enable “import src…”

from src import (
    SolarHaloModel, build_models_for_phi_values, CosmicRayLIS,
    setup_paper_style,
    MODEL_COLORS, DATA_COLOR, DATA_MARKER, DATA_MS, DATA_CAPSIZE,
)
from src.io import load_results                    # loads real_data.pkl


# ════════════════════════════════════════════════════════════════════
# Utility helpers
# ════════════════════════════════════════════════════════════════════
def load_real_dataset() -> dict:
    results_file = ROOT / "results" / "real_data.pkl"
    if not results_file.exists():
        raise FileNotFoundError(
            f"\n\n{results_file} not found.\n"
            "Run the main pipeline first (e.g. ./run_on_real_data.sh) "
            "so that the real Fermi-LAT products are created.\n"
        )
    return load_results(results_file)


def save(fig: plt.Figure, name: str):
    outdir = ROOT / "plots" / "output"
    outdir.mkdir(parents=True, exist_ok=True)
    fig.savefig(outdir / f"{name}.png", dpi=300, bbox_inches="tight")
    fig.savefig(outdir / f"{name}.pdf", bbox_inches="tight")
    print(f"   → {name}.png / {name}.pdf")


# ════════════════════════════════════════════════════════════════════
# Figure-building routines
# ════════════════════════════════════════════════════════════════════

PHI_VALUES  = [0, 500, 1000]
PHI_LABELS  = {0: "0 MV", 500: "500 MV", 1000: "1000 MV"}


def figure_1(models, data):
    """Spectrum in 5–10° annulus & radial profile at 1–3 GeV."""
    fig, axes = plt.subplots(2, 1, figsize=(4.6, 7.0))
    fig.subplots_adjust(hspace=0.35)

    # ── (a) Spectrum ──────────────────────────────────────────────
    ax = axes[0]
    E = np.logspace(-1.5, 2, 200)   # 0.03–100 GeV
    for phi in PHI_VALUES:
        ax.loglog(E,
                  models[phi].spectrum_in_angular_bin(5, 10, E),
                  color=MODEL_COLORS[phi], lw=1.8, label=PHI_LABELS[phi])

    d = data["spectrum_data"]["5-10"]
    good = ~d["upper_lim"]
    ax.errorbar(d["E_GeV"][good], d["flux"][good], yerr=d["flux_err"][good],
                fmt=DATA_MARKER, color=DATA_COLOR, ms=DATA_MS,
                capsize=DATA_CAPSIZE, lw=0.8, label="Data (1 yr)")

    ax.set_xlabel("Energy (GeV)")
    ax.set_ylabel(r"$E^2\,dN/dE$  ($10^{-8}$ GeV cm$^{-2}$ s$^{-1}$ sr$^{-1}$)")
    ax.set_xlim(0.03, 100)
    ax.set_ylim(1, 100)
    ax.legend(fontsize=7.5, loc="upper right")
    ax.text(0.04, 0.92, "5–10°", transform=ax.transAxes,
            fontsize=9, va="top",
            bbox=dict(facecolor="white", alpha=0.8, edgecolor="lightgray", pad=2))
    ax.set_title("Spectrum — Solar ICS Halo (1 yr)", fontsize=10)

    # ── (b) Radial profile 1–3 GeV ───────────────────────────────
    ax = axes[1]
    theta = np.linspace(2, 45, 200)
    for phi in PHI_VALUES:
        ax.semilogy(theta,
                    models[phi].radial_profile_in_energy_bin(1.0, 3.16, theta),
                    color=MODEL_COLORS[phi], lw=1.8, label=PHI_LABELS[phi])

    d = data["radial_data"]["1.0-3.1 GeV"]
    ax.errorbar(d["theta_deg"], d["flux"], yerr=d["flux_err"],
                fmt=DATA_MARKER, color=DATA_COLOR, ms=DATA_MS,
                capsize=DATA_CAPSIZE, lw=0.8)

    ax.set_xlabel("Angular Distance to the Sun (°)")
    ax.set_ylabel(r"$E^2\,dN/dE$  ($10^{-8}$ GeV cm$^{-2}$ s$^{-1}$ sr$^{-1}$)")
    ax.set_xlim(3, 45)
    ax.set_ylim(0.5, 200)
    ax.legend(fontsize=7.5, loc="upper right")
    ax.text(0.96, 0.92, "1–3 GeV", transform=ax.transAxes,
            fontsize=9, ha="right", va="top",
            bbox=dict(facecolor="white", alpha=0.8, edgecolor="lightgray", pad=2))
    ax.set_title("Radial Profile — Solar ICS Halo (1 yr)", fontsize=10)
    return fig


def figure_2(data):
    """Six helioprojective maps: data, background, disk, halo, σ-maps."""
    hm = data["helio_map"]
    Tx, Ty = hm["Tx"], hm["Ty"]
    TxG, TyG = np.meshgrid(Tx, Ty)
    r = np.sqrt(TxG**2 + TyG**2)
    mask = r > 45

    # Simple analytic solar-disk model for the visual panel
    disk = np.where(r < 2.5, 500.0, 0.0)

    counts   = hm["data"]
    bg       = hm["background"]
    halo     = hm["halo"]
    resid    = counts - bg - disk
    sigma    = np.where(counts > 0, resid / np.sqrt(np.abs(counts) + 1), 0)
    sigma    = np.clip(sigma, -4, 9)

    panels = [
        ("Fermi-LAT Data\n1–3 GeV",  counts, 'counts', 'viridis',  (50, 1000)),
        ("Background Model",         bg,     'counts', 'viridis',  (50, 1000)),
        ("Solar Disk Model",         disk,   'log',    'viridis',  (0.1, 600)),
        ("Solar Halo Model",         halo,   'log',    'viridis',  (0.1, 30)),
        ("Halo + Residual (σ)",      sigma,  'linear', 'RdYlBu_r', (-4, 9)),
        ("Residual (σ)",             sigma,  'linear', 'RdYlBu_r', (-4, 9)),
    ]
    cbar_lbl = {'counts': 'Counts deg⁻²', 'log': 'Counts (norm.)', 'linear': 'σ'}

    fig = plt.figure(figsize=(8.5, 5.5))
    gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.08, wspace=0.12)

    for i, (title, img, scale, cmap, clim) in enumerate(panels):
        ax = fig.add_subplot(gs[i//2, i % 2])
        shown = np.where(mask, np.nan, img.astype(float))

        if scale == 'log':
            shown = np.clip(shown, clim[0], None)
            im = ax.imshow(shown, origin='lower', extent=[-45, 45, -45, 45],
                           norm=LogNorm(vmin=clim[0], vmax=clim[1]),
                           cmap=cmap, aspect='equal')
        else:
            im = ax.imshow(shown, origin='lower', extent=[-45, 45, -45, 45],
                           vmin=clim[0], vmax=clim[1], cmap=cmap, aspect='equal')

        # boundary circle
        ang = np.linspace(0, 2*np.pi, 400)
        ax.plot(45*np.cos(ang), 45*np.sin(ang), 'w-', lw=0.6, alpha=0.6)

        ax.text(0.04, 0.96, title, transform=ax.transAxes,
                fontsize=7.0, ha='left', va='top',
                bbox=dict(facecolor='black', alpha=0.45, edgecolor='none', pad=1.5),
                color='white')

        if i//2 == 2: ax.set_xlabel('Tₓ (°)', fontsize=7.5)
        else:         ax.set_xticklabels([])
        if i % 2 == 0: ax.set_ylabel('Tᵧ (°)', fontsize=7.5)
        else:          ax.set_yticklabels([])

        ax.tick_params(labelsize=6.5)
        plt.colorbar(im, ax=ax, fraction=0.04, pad=0.01,
                     label=cbar_lbl[scale]).ax.tick_params(labelsize=6)

    fig.suptitle('Fermi-LAT Solar Halo — 1–3 GeV (1 yr)', fontsize=9.2, y=1.01)
    return fig


def figure_3(models, data):
    """Eight annular spectra plots."""
    bins = [
        ('<2.5',  '<2.5°',   0.0,  2.5),
        ('2.5-5', '2.5–5°',  2.5,  5.0),
        ('5-10',  '5–10°',   5.0, 10.0),
        ('10-15', '10–15°', 10.0, 15.0),
        ('15-20', '15–20°', 15.0, 20.0),
        ('20-25', '20–25°', 20.0, 25.0),
        ('25-35', '25–35°', 25.0, 35.0),
        ('35-45', '35–45°', 35.0, 45.0),
    ]
    E = np.logspace(-1.5, 2, 200)

    fig, axes = plt.subplots(4, 2, figsize=(7.0, 9.5))
    fig.subplots_adjust(hspace=0.06, wspace=0.06)
    ax_flat = axes.flatten(order='F')

    for idx, (key, label, th0, th1) in enumerate(bins):
        ax = ax_flat[idx]
        for phi in PHI_VALUES:
            ax.loglog(E,
                      models[phi].spectrum_in_angular_bin(th0, th1, E),
                      color=MODEL_COLORS[phi], lw=1.6)
        d = data["spectrum_data"][key]
        good = ~d["upper_lim"]
        ax.errorbar(d["E_GeV"][good], d["flux"][good], yerr=d["flux_err"][good],
                    fmt=DATA_MARKER, color=DATA_COLOR, ms=3.5,
                    capsize=2.5, lw=0.8, zorder=5)
        ax.text(0.97, 0.96, label, transform=ax.transAxes,
                fontsize=8, ha='right', va='top')
        ax.set_xlim(0.05, 50)
        ax.set_ylim(1, 200)
        if idx // 4 == 3: ax.set_xlabel('Energy (GeV)', fontsize=8.5)
        else:             ax.set_xticklabels([])
        if idx % 4 == 0:
            ax.set_ylabel(r'$E^2\,dN/dE$  ($10^{-8}$ GeV cm$^{-2}$ s$^{-1}$ sr$^{-1}$)',
                          fontsize=7.5)
        else:
            ax.set_yticklabels([])
        ax.tick_params(which='both', direction='in', top=True, right=True, labelsize=7.5)

    ax_flat[0].legend(
        [plt.Line2D([0],[0], color=MODEL_COLORS[p], lw=1.6) for p in PHI_VALUES] +
        [plt.Line2D([0],[0], marker=DATA_MARKER, color=DATA_COLOR, lw=0, ms=3.5)],
        ['0 MV', '500 MV', '1000 MV', 'Data (1 yr)'],
        fontsize=6.5, loc='lower right', framealpha=0.85, handlelength=1.5)

    fig.suptitle('Solar ICS Halo Spectra in Radial Bins (1 yr)', fontsize=9.2, y=1.01)
    return fig


def figure_4(models, data):
    """Six radial-profile plots (energy bins)."""
    E_bins = [
        ('0.03-0.1 GeV',  '0.03–0.1 GeV',   0.03,  0.1),
        ('0.1-0.31 GeV',  '0.1–0.31 GeV',   0.1,   0.31),
        ('0.31-1.0 GeV',  '0.31–1.0 GeV',   0.31,  1.0),
        ('1.0-3.1 GeV',   '1.0–3.1 GeV',    1.0,   3.1),
        ('3.1-10.0 GeV',  '3.1–10 GeV',     3.1,  10.0),
        ('10-100 GeV',    '10–100 GeV',    10.0, 100.0),
    ]
    theta_f = np.linspace(3, 45, 200)

    fig, axes = plt.subplots(3, 2, figsize=(7.0, 7.5))
    fig.subplots_adjust(hspace=0.06, wspace=0.06)
    ax_flat = axes.flatten(order='F')

    for idx, (key, label, E0, E1) in enumerate(E_bins):
        ax = ax_flat[idx]
        for phi in PHI_VALUES:
            ax.semilogy(theta_f,
                        models[phi].radial_profile_in_energy_bin(E0, E1, theta_f),
                        color=MODEL_COLORS[phi], lw=1.6)
        d = data["radial_data"][key]
        ax.errorbar(d["theta_deg"], d["flux"], yerr=d["flux_err"],
                    fmt=DATA_MARKER, color=DATA_COLOR, ms=3.5,
                    capsize=2.5, lw=0.8, zorder=5)
        ax.text(0.97, 0.96, label, transform=ax.transAxes,
                fontsize=7.5, ha='right', va='top')
        ax.set_xlim(3, 45)
        ax.set_ylim(0.8, 200)
        ax.xaxis.set_minor_locator(plt.MultipleLocator(5))
        if idx // 3 == 2: ax.set_xlabel('Angular Distance to the Sun (°)', fontsize=8.5)
        else:             ax.set_xticklabels([])
        if idx % 3 == 0:
            ax.set_ylabel(r'$E^2\,dN/dE$  ($10^{-8}$ GeV cm$^{-2}$ s$^{-1}$ sr$^{-1}$)',
                          fontsize=7.5)
        else:
            ax.set_yticklabels([])
        ax.tick_params(which='both', direction='in', top=True, right=True, labelsize=7.5)

    ax_flat[2].legend(
        [plt.Line2D([0],[0], color=MODEL_COLORS[p], lw=1.6) for p in PHI_VALUES] +
        [plt.Line2D([0],[0], marker=DATA_MARKER, color=DATA_COLOR, lw=0, ms=3.5)],
        ['0 MV', '500 MV', '1000 MV', 'Data (1 yr)'],
        fontsize=6.5, loc='lower left', framealpha=0.85, handlelength=1.5)

    fig.suptitle('Solar ICS Halo Radial Profiles in Energy Bins (1 yr)',
                 fontsize=9.2, y=1.01)
    return fig


# ════════════════════════════════════════════════════════════════════
# Main driver
# ════════════════════════════════════════════════════════════════════
def main():
    os.makedirs(ROOT / "plots" / "output", exist_ok=True)
    setup_paper_style()

    print("="*62)
    print("  Solar ICS Halo — Figure Reproduction  (real 1-year data)")
    print("="*62)

    # real Fermi-LAT data (raises if missing)
    data = load_real_dataset()

    # physics models
    lis = CosmicRayLIS()
    models = build_models_for_phi_values(PHI_VALUES, lis)

    # make & save figures
    save(figure_1(models, data), "fig1_spectrum_morphology")
    save(figure_2(data),        "fig2_helioprojective_maps")
    save(figure_3(models, data),"fig3_spectra_radial_bins")
    save(figure_4(models, data),"fig4_radial_profiles_energy_bins")

    print("\n✓ All four figures written to plots/output/")

if __name__ == "__main__":
    main()
